swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /gists/{id}/commits:
    x-swagger-router-controller: gistCommits
    get:
      description: Returns list of commits for a specified gist
      operationId: listGistCommits
      parameters:
        - name: id
          in: path
          description: Identifier of the gist for which to pull the list of commits
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/GistCommitsResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"

  /gists/{id}/star:
    x-swagger-router-controller: gists
    delete:
      summary: deletes a start
      description: this will delete a star on a gist
      operationId: removeStar
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
      parameters:
         - in: path
           name: id
           required: true
           description: id of gist
           type: string
    put:
      summary: add a start
      description: this will add a star on a gist
      operationId: addStar
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HelloWorldResponse"
      parameters:
        - in: path
          name: id
          required: true
          description: id of gist
          type: string
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  GistCommitsResponse:
    type: "array"
    items:
      required:
        - url
        - version
        - user
      properties:
        url:
          type: string
        version:
          type: string
        user:
          $ref: "#/definitions/User"
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  User:
    required:
      - login
      - id
    properties:
      id:
        type: number
      login:
        type: string
